### ISSUE TITLE
Merge this widget in the django-dashing project

### ISSUE THREAD

**Issue by mtdb** [torstenfeld/django-dashing-widget-knob#1]
Hi Torsten, I am letting you know that I am planning to launch version 0.3 of django-dashing soon, then I hope to launch with this some additional widgets as default widgets (an image widget, a map widget and a knob widget). Then I request you that you create this widget in a branch called widget/knob in the django-dashing repository, or give me permission to copy your code and include it in the project if it is possible.

Take into consideration that this widget will need some changes to be compatible with version 0.3:
https://github.com/talpor/django-dashing/commit/a83efe0b450d0f80e519a3d0df2a7d2a520e1af2
https://github.com/talpor/django-dashing/commit/8f2ae636e95fa1a653939b53a08076848335b929

Waiting for your reply!

**Comment by torstenfeld** [comment]
Hi Mauricio, I will have a look into that this weekend. From my point of view, the knob widget is not as stable as I'd like it to be, as sometimes (especially if it's not on the first dashboard in a dashboard set).

When you're going to take over the code, will you do the changes necessary to be 0.3 compatible?

Sorry for the late reply :)

**Comment by torstenfeld** [comment]
@individuo7 created a pull request into django-dashing development branch
